# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build"
  lane :build_debug_app do
    gradle(task: "assembleDebug")
  end


  desc "Submit to Firebase"
  lane :beta do
    gradle(task: "assembleRelease")
    firebase_app_distribution(
      app: "1:217734547318:android:2008dd3a68f90b48a69c57",
      testers: "tadashi.nemoto0713@gmail.com",
      apk_path: "app/build/outputs/apk/release/app-release.apk",
      firebase_cli_token: ENV["FIREBASE_TOKEN"]
    )
  end
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
end
